IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/models.py
# class Toy:
#     def __init__(self, id, image, name, price, category, description):
#         self.id = id
#         self.image = image
#         self.name = name
#         self.price = price
#         self.category = category
#         self.description = description

#     def get_toy_detail(self):
#         return str(self)
    
#     def __repr__(self):
#         str = "ID: {}, Image: {}, Name: {}, Price: {}, Category: {}, description: {} \n"
#         str = str.format(self.id, self.image, self.name, self.price, self.category, self.description)
#         return str

from . import db

class Toy(db.Model):
    __tablename__ = 'toys'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    image = db.Column(db.String(64), nullable=False)
    price = db.Column(db.Integer, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    description = db.Column(db.String(500), nullable=False, default='There is no description.')

    def __repr__(self):
         str = "ID: {}, Name: {}, Image: {}, Price: {}, Category_id: {}, Description: {}\n"
         str = str.format(self.id, self.name, self.image, self.price, self.category_id, self.description)
         return str

class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True) 
    toy_id = db.Column(db.Integer, db.ForeignKey('toys.id'), primary_key=True)
    amount = db.Column(db.Integer, nullable=False)
    total_price = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        str = "ID: {}, Toy ID: {}, Order Detail ID: {}, Amount: {}, Total Price: {}\n" 
        str = str.format(self.id, self.toy_id, self.order_detail_id, self.amount, self.total_price)
        return str
    
    
class Order_detail(db.Model):
    __tablename__ = 'order_details'
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey('orders.id'))
    firstname = db.Column(db.String(64), nullable=False)
    lastname = db.Column(db.String(64), nullable=False)
    email = db.Column(db.String(64), nullable=False)
    address = db.Column(db.String(64), nullable=False)

    def __repr__(self):
        str = "ID: {}, First Name: {}, Last Name: {}, Email: {}, Address: {}\n" 
        str = str.format(self.id, self.firstname, self.lastname, self.email, self.address)
        return str
    
class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False, unique=True)

    def __repr__(self):
        str = "ID: {}, Name: {}\n"
        str = str.format(self.id, self.name)
        return super().__repr__()

class ContactUs(db.Model):
    __tablename__ = 'contactus'
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(64))
    lastname = db.Column(db.String(64))
    email = db.Column(db.String(64))
    comment = db.Column(db.String(500))

    def __repr__(self):
        str = "ID: {}, First Name: {}, Last Name: {}, Email: {}, Comment: {}\n"
        str = str.format(self.id, self.firstname, self.lastname, self.email, self.comment)
        return str

    

IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()
app=Flask(__name__)
def create_app():
    
    app.debug=True
    app.secret_key='ThisIsASecretKey'

    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///toy.sqlite'

    db.init_app(app)

    bootstrap = Bootstrap4(app)

    from . import views
    app.register_blueprint(views.bp)
    # from . import admin
    # app.register_blueprint(admin.bp)

    return app

@app.errorhandler(404)
def not_found(e):
    return render_template("404.html")

@app.errorhandler(500)
def internal_error(e):
    return render_template("500.html")

IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Toy, Order_detail, Order
from . import db
# This data will eventually be stored in a database
# HelloKitty = Toy(1, 'HelloKitty.jpg', 'HelloKitty', '$10', 'plushi','This adorable Hello Kitty plushie features soft, cuddly fabric and a cute pink bow. With her friendly smile, she is perfect for hugs, decoration, and gifting to Hello Kitty fans of all ages.')
# IronMan = Toy(2, 'ironMan.jpg', 'IronMan', '$100', 'collection', 'Marvel at the ultimate Iron Man collection: suits, gadgets, and comics galore, embodying heroism, innovation, and technological prowess.')
# toys = [HelloKitty, IronMan]

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    toys = Toy.query.order_by(Toy.name).all()
    order=checkSession()
    # return render_template('Homepage.html', toybox = toys)
    return render_template('Homepage.html', toys = toys, order = order)

@bp.route('/category/<int:category>')
def category(category):
    match category:
        case 1:
            toys = Toy.query.filter(Toy.category_id == category).all()
        case 2:
            toys = Toy.query.filter(Toy.category_id == category).all()
        case 3:
            toys = Toy.query.filter(Toy.category_id == category).all()
        case 4:
            toys = Toy.query.order_by(Toy.name).all()

    return render_template('Homepage.html', toys = toys)
    
@bp.route('/toys')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    toys = Toy.query.filter(Toy.name.like(search)).all()
    return render_template('Homepage.html', toys = toys)


# @bp.route('/ProductDetailPage/<int:toyid>/')
# def toys(toyid):
#     newToyBoxs = []
#     for Toy in toys:
#         if int(Toy.id) == int(toyid):
#             newToyBoxs.append(Toy)
#     return render_template('ProductDetailPage.html', toybox = newToyBoxs)

@bp.route('/toy/<int:toyid>/')
def toydetail(toyid):
    toys = Toy.query.all()
    toy = Toy.query.filter(Toy.id == toyid).first()
    print(toy.image)
    return render_template('ProductDetailPage.html', toy = toy, toys = toys)



#orderDetail function (Ian)
@bp.route('/checkout', methods=['POST','GET'])
def checkout():
    order_detail = Order_detail(order_id = request.values.get('order_id'), 
                                firstname = request.values.get('firstname'), 
                                lastname = request.values.get('lastname'),
                                email = request.values.get('email'),
                                address = request.values.get('address'))
    
    try:
        db.session.add(order_detail)
        db.session.commit()
        flash('Thanks for order')
        return redirect(url_for('main.index'))
    
    except:
        flash('There was an issue completing your order')
        return redirect(url_for('main.index'))    

@bp.route('/check')
def check():
    return render_template('Orderdetail.html')

@bp.route('/add/<int:toyid>/')
def add(toyid):
    order = checkSession()
    toy = Toy.query.filter(Toy.id == toyid).first()

    order_check = Order.query.where((Order.toy_id == toyid) & (Order.id == order.id))
    if order_check == None:
        print('check(1')
        o1 = Order()
        o1.id = order.id
        o1.toy_id = toyid
        o1.amount = 1
        o1.total_price = toy.price * o1.amount
        db.session.add(o1)
    else:
        print('check(2')
        order_check.amount += 1
        order_check.total_price = toy.price * order_check.amount

    try:
        db.session.commit()
        flash('add toy complete')
    except Exception as e:
        print('check(3)')
        print(e)
        flash('add failed')



def checkSession():
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']).first())

    else:
        order = None

    if order is None:
        order = Order()
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id']=order.id
        except Exception as e:
            print(e)
            print('Fail')

    return order



IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/Homepage.html
{% extends 'base.html' %}

{% block header %}
<div id="navigationbar">
    <div id="companyname">
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
        <a href="#">My Fantastic Toy Shop</a>
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
    </div>
    <nav id="navigationmenu">
        <ul id="navigationlist">
            <li>
                <a href="#companyname">Homepage</a>
            </li>
            <li>
                <a href="#products">Products</a>
            </li>
            <li>
                <a href="#contactUs">Contact Us</a>
            </li>
            <li>
                <a href="#aboutUs">About Us</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block main %}
<!-- Hot-selling -->
<section>        
    <div class="d-flex flex-row" style="margin-left: 10%;">
        <div class="p-2">
            <div style="height: 44px;width: 44px;">
                <img src="{{url_for('static', filename='image/Icon/hot.png')}}" alt="hot" style="height: 44px; width: 44px;">
            </div>
        </div>
        <div class="p-2">
            <div style="height: 50px; width: 300px;">
                <h1 style="color: #ffffff;">Hot-Selling Toys</h1>
            </div>
        </div>

    </div>

    <div class="container" style="align-items: center;">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{url_for('static', filename='image/Mario.jpg')}}" class="d-block w-100" alt="Mario" height="480px" width="600px" style="border-radius: 4px;">
              </div>
              <div class="carousel-item">
                <img src="{{url_for('static', filename='image/sheep.jpg')}}" class="d-block w-100" alt="sheep" height="480px" width="600px" style="border-radius: 4px;">
              </div>
              <div class="carousel-item">
                <img src="{{url_for('static', filename='image/chess.jpg')}}" class="d-block w-100" alt="chess" height="480px" width="600px" style="border-radius: 4px;">
              </div>
            </div>
           <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </button>
         </div>
    </div>           
</section>

<!-- Filter & search -->
<section>
    <div class="d-flex flex-row" style="margin-left: 10%;" id="products">
        <div class="p-2">
            <div style="height: 44px;width: 44px;">
                <img src="{{url_for('static', filename='image/Icon/toys.png')}}" alt="toys" style="height: 44px; width: 44px;">
            </div>
        </div>
        <div class="p-2">
            <div style="height: 50px; width: 300px;">
                <h1 style="color: #ffffff;">Products</h1>
            </div>
        </div> 
    </div>

    <div style="margin-left: 11.5%;">
        <form action="{{url_for('main.search')}}">
            <input class="form-control" type="search" placeholder="Seearch Toys..." style="width: 250px; display: inline;" name="search">
            <button type="submit" style="background-color: transparent; border: none; display: inline;">
            <img src="{{url_for('static', filename='image/Icon/search.png')}}" alt="search" style="height: 45px;width: 45px;">
        </button>
        </form>
        <div class="dropdown" style="background-color: lightsalmon; display: inline;">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="Categories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: rgb(255, 115, 60);">
                Categories
            </button>
            <div class="dropdown-menu" aria-labelledby="Categories">
              <a class="dropdown-item" href="{{url_for('main.category', category=4)}}">All</a>
              <a class="dropdown-item" href="{{url_for('main.category', category=1)}}">Plushie</a>
              <a class="dropdown-item" href="{{url_for('main.category', category=2)}}">Collection</a>
              <a class="dropdown-item" href="{{url_for('main.category', category=3)}}">Boardgame</a>
            </div>
        </div>
     </div> 
</section>

<!-- Product --> <!--order model(Ian)-->
<section>
    <div class="row" style="margin-left: 6%; margin-right: 6%;">
        {% for Toy in toys %}
        <div class="col-4">
            <div class="card_Product">
                <img class="card-img-top" src="{{url_for('static', filename='image/'+Toy.image)}}" alt="Card image">
                <div class="d-flex flex-column card-body">
                  <p class="card-text">{{Toy.name}}</p>
                  <p class="card-text">{{Toy.description}}</p>
        
                  <div class="d-flex">
                    <div class="mr-auto p-2">
                        <a href="{{url_for('main.toydetail', toyid=Toy.id)}}">
                            <button class="button_Icon mt-auto">
                                <img src="{{url_for('static', filename='image/Icon/details.png')}}" alt="details" style="height: 44px;width: 44px;">
                            </button>
                        </a>
                    </div>
                    <div class="p-2">
                        <form action="{{url_for('main.add', toyid=Toy.id)}}">
                            <button class="button_Icon mt-auto">
                                <img src="{{url_for('static', filename='image/Icon/add-to-cart.png')}}" alt="details" style="height: 44px;width: 44px;">
                            </button>
                        </form>
                    </div>
                  </div>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</section>

<!-- ContactUs -->
<section>
    <div class="d-flex flex-row" style="margin-left: 10%;" id="contactUs">
        <div class="p-2">
            <div style="height: 44px;width: 44px;">
                <img src="{{url_for('static', filename='image/Icon/mail.png')}}" alt="contactUs" style="height: 44px; width: 44px;">
            </div>
        </div>
        <div class="p-2">
            <div style="height: 50px; width: 300px;">
                <h1 style="color: #ffffff;">Contact Us</h1>
            </div>
        </div>
    </div>

    <div class="container" style="width: 600px; margin-left: 12%;">
        <form action="action_page.php">
            <div class="d-flex flex-row">
                <div class="p-2">
                    <label for="fname">First Name:</label>
                    <input type="text" id="fname" name="firstname" placeholder="Your name..">
                </div>
                <div class="p-2">
                    <label for="lname">Last Name:</label>
                    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
                </div>
            </div>

            <div class="d-flex flex-column">
                <div class="p-2">
                    <label for="Email">Email:</label>
                    <input type="email" id="Email" name="Email" placeholder="Your email.." style=" width: 505px; border: 1px solid #ccc; border-radius: 4px;">
                </div>
                <div class="p-2">
                    <label for="comment">Comment:</label>
                    <textarea id="comment" name="comment" placeholder="Write something.." style="height:200px"></textarea>
                </div>
                <div class="p-2">
                    <input type="submit" value="Submit">
                </div>
              </div>
        </form>
      </div>
</section>

<!-- aboutUs -->
<section>
    <div class="d-flex flex-row" style="margin-left: 10%;" id="aboutUs">
        <div class="p-2">
            <div style="height: 44px;width: 44px;">
                <img src="{{url_for('static', filename='image/Icon/man.png')}}" alt="contactUs" style="height: 44px; width: 44px;">
            </div>
        </div>
        <div class="p-2">
            <div style="height: 50px; width: 300px;">
                <h1 style="color: #ffffff;">About Us</h1>
            </div>
        </div>
    </div>

    <div class="container" style=" margin-left: 12%; background-color: transparent; margin-top: -30px;">
        
        <div class="d-flex flex-row">
            <div class="p-2" style="width: 35%;">
                <div class="d-flex flex-column">
                    <div class="p-2">
                        <h2 style="color: #ffffff; display: inline;">Company:</h2>
                        <p style="color: #ffffff; display: inline; margin-left: 1%;">HappyLife.co</p>    
                    </div>
                    <div class="p-2">
                        <h2 style="color: #ffffff; display: inline;">Email:</h2>
                        <p style="color: #ffffff; display: inline; margin-left: 1%;">Happylife123@haha.com</p>
                    </div>
                    <div class="p-2">
                        <h2 style="color: #ffffff; display: inline;">Phone Number:</h2>
                        <p style="color: #ffffff; display: inline;margin-left: 1%;">(+61)413123123</p>     
                    </div>
                </div>
            </div>

            <div class="p-2" style="margin-top: 25px; margin-left: 30px;">
                <a href="https://www.facebook.com/">
                    <button type="button" style="background-color: transparent;  border: none; background-size: auto; background-position: center;">
                        <div>
                            <img src="{{url_for('static', filename='image/Icon/facebook.png')}}", alt="facebook" style="height: 120px; width: 120px;">
                        </div>
                    </button>
                </a>
            </div>

            <div class="p-2" style="margin-top: 25px; margin-left: 30px;">
                <a href="https://www.instagram.com/">
                    <button type="button" style="background-color: transparent;  border: none; background-size: auto; background-position: center;">
                        <div>
                            <img src="{{url_for('static', filename='image/Icon/instagram.png')}}", alt="instagram" style="height: 120px; width: 120px;">
                        </div>
                    </button>
                </a>                           
            </div>

            <div class="p-2" style="margin-top: 25px; margin-left: 30px;">
                <a href="https://x.com/">
                    <button type="button" style="background-color: transparent;  border: none; background-size: auto; background-position: center;">
                        <div>
                            <img src="{{url_for('static', filename='image/Icon/twitter.png')}}", alt="twitter" style="height: 120px; width: 120px;">
                        </div>
                    </button>
                </a>
            </div>   
        </div>
    </div>
</section>
{% endblock %}

IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/Orderdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="My Fantastic Toy Shop" />
    <title>My Fantastic Toy Shop</title>
  
</head>
<body style="background-color: lightsalmon;">

        <div class="container col-md-6">
          <h2>Checkout Form</h2>
          
          <form action="{{url_for('main.checkout')}}", methods="POST">
             
            <div class="form-group">
              <label for="firstname">First name:</label>
              <input type="text" class="form-control" id="firstname" placeholder="Enter first name" name="firstname">
            </div>
          
            <div class="form-group">
              <label for="lastname">Lastname:</label>
              <input type="text" class="form-control" id="lastname" placeholder="Enter lastname" name="lastname">
            </div>
        
            <div class="form-group">
              <label for="email">Email:</label>
              <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
            </div>
        
            <div class="form-group">
              <label for="address">Adress:</label>
              <input type="text" class="form-control" id="address" placeholder="Enter address" name="address">
            </div>
        
            <button type="submit" class="btn btn-default">Submit</button>
         
          </form>
        </div>
    
    <!-- Footer of the website -->
    <footer>
        <div class="footer">
            <p>Copyright &copy; 2024</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</body>
</html>

IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/ProductDetailPage.html
{% extends 'base.html' %}


{% block header %}
<div id="navigationbar">
    <div id="companyname">
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
        <a href="#">My Fantastic Toy Shop</a>
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
    </div>
    <nav id="navigationmenu">
        <ul id="navigationlist">
            <li>
                <a href="{{url_for('main.index')}}">
                    <img style="height: 24px; width: 24px;" src="{{url_for('static', filename='image/Icon/back.png')}}" alt="back">
                    Back
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block main %}
<section>
    <div style="align-items: center; border-bottom: 4px solid white; margin-left: 10%; margin-right: 10%; margin-top: 3%;" id="productdetail">
        <div class="d-flex flex-row">
            <div class="p-2">
                <img src="{{url_for('static', filename='image/Icon/info.png')}}" alt="info" style="height: 36px; width: 36px;">
            </div>
            <div class="p-2">
                <div style="height: 50px; width: 300px; margin-left: -5%;">
                    <h2 style="color: white;">Toy Detail:</h2>
                </div>
            </div> 
        </div>

        <div class="d-flex flex-column">
            <div class="p-2" style="margin-top: -1%; width: 300px;">
                <img src="{{url_for('static', filename='image/'+toy.image)}}" alt="toyImg" style=" width: 300px; height: 300px; border-radius: 4px; border: 4px solid white;">
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Name:</h2>
                <p style="color: white; display: inline; margin-left: 1%;">{{toy.name}}</p>
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Price:</h2>
                <p style="color: white; display: inline; margin-left: 1%;">${{toy.price}}</p>
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Category:</h2>
                <p style="color: white; display: inline; margin-left: 1%;">{{toy.category_id.name}}</p>
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Description:</h2>
                <p style="color: white; display: inline; margin-left: 1%;"><br>{{toy.description}}</p>
            </div>

            <div class="p-2">
                <form action="{{url_for('main.add', toyid=toy.id)}}">
                    <button style="background-color: rgb(255, 115, 60); width: 180px; height: 60px; border-radius: 30px; border-color: rgb(215, 95, 50); color: white;">
                        Add In Cart!
                        <img src="{{url_for('static', filename='image/Icon/add-to-cart.png')}}" alt="details" style="height: 44px;width: 44px;">
                    </button>
                </form>
            </div>
        </div>  
    </div>
</section>

<!-- Relative Product -->
<section>
    <div style="align-items: center; margin-left: 10%; margin-right: 10%;margin-top: 1%; margin-bottom: 5%;" id="relatedtoys">
        <div class="d-flex flex-row">
            <div class="p-2">
                <img src="{{url_for('static', filename='image/Icon/related-toys.png')}}" alt="info" style="height: 36px; width: 36px;">
            </div>
            <div class="p-2">
                <div style="height: 50px; width: 300px; margin-left: -5%;">
                    <h2 style="color: white;">Related Toys:</h2>
                </div>
            </div> 
        </div>

        <div class="container" style="padding: 5px; background-color: rgb(185, 80, 25);">
            <div class="scrolling-wrapper">

                {% for Toy in toys %}
                <a href="{{url_for('main.toydetail', toyid=Toy.id)}}"> <!-- route error -->
                    <div class="card_Product_related">
                        <img class="card-img-top" src="{{url_for('static', filename='image/'+Toy.image)}}" alt="Card name">
                        <div class="card-body">
                          <p class="card-text" style="color: black;">{{Toy.name}}</p>
                        </div>
                    </div>
                </a>
                {% endfor %}

            </div>
        </div>
    </div>
</section>
{% endblock %}

IFN557_assignment-Ian/N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/temparary.html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="width: 300px;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img   src="../static/image/HelloKitty.jpg" alt="HelloKitty" style=" width: 300px; height: 300px; border-radius: 4px; border: 4px solid white;">
      </div>
      <div class="carousel-item">
        <img  src="../static/image/HelloKitty1.jpg" alt="HelloKitty" style=" width: 300px; height: 300px; border-radius: 4px; border: 4px solid white;">
      </div>
    </div>
   <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
 </div>