N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Toy, Order, Order_detail, ContactUs, Category
from sqlalchemy.orm import aliased
from . import db

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    toys = Toy.query.order_by(Toy.name).all()
    orders = checkorder()
    return render_template('Homepage.html', toys = toys, orders = orders)

@bp.route('/category/<int:category>')
def category(category):
    match category:
        case 1:
            toys = Toy.query.filter(Toy.category_id == category).all()
        case 2:
            toys = Toy.query.filter(Toy.category_id == category).all()
        case 3:
            toys = Toy.query.filter(Toy.category_id == category).all()
        case 4:
            toys = Toy.query.order_by(Toy.name).all()

    return render_template('Homepage.html', toys = toys)
    
@bp.route('/toys')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    toys = Toy.query.filter(Toy.name.like(search)).all()
    return render_template('Homepage.html', toys = toys)

@bp.route('/toy/<int:toyid>/')
def toydetail(toyid):
    toys = Toy.query.order_by(Toy.name).all()
    category_alias = aliased(Category)
    toy = db.session.query(Toy.id, Toy.name.label('toy_name'), Toy.image, Toy.description,Toy.price, category_alias.name.label('category_name')).join(category_alias, Toy.category_id==category_alias.id).filter(Toy.id == toyid).first()
    orders = checkorder()
    return render_template('ProductDetailPage.html', toy = toy, toys = toys, orders = orders)

@bp.route('/submit', methods=['POST','GET'])
def submit():
    contactus = ContactUs(firstname = request.values.get('firstname'), 
                          lastname = request.values.get('lastname'), 
                          email = str(request.values.get('Email')), 
                          comment = request.values.get('comment'))
    
    db.session.add(contactus)

    try:
        db.session.commit()
        flash('Thank you for your submit!')

    except Exception as e:
        db.session.rollback()
        flash('Submit fail...')
        print(e)

    return redirect(url_for('main.index'))

# checkout function #Bryan
@bp.route('/checkout', methods=['POST','GET'])
def checkout():

    # check order exist or not
    if 'order_id' not in session:
            flash('No active order found.')
            return redirect(url_for('main.index'))
    
    order_id = session.get('order_id')
    order = Order.query.get(order_id)

    if order is None:
            flash('Order not found.')
            return redirect(url_for('main.index'))
    
    # update order detail
    order.firstname = request.values.get('firstname')
    order.lastname = request.values.get('lastname')
    order.email = request.values.get('email')
    order.address = request.values.get('address')

    try:
        db.session.commit()
        flash('Order updated successfully!')
        order = createOrder()
        toys = Toy.query.order_by(Toy.name).all()
        return render_template('Homepage.html', toys = toys, orders = [])
    except Exception as e:
        db.session.rollback()
        flash(f'Error updating order: {e}')
        return redirect(url_for('main.checkout'))


# navigate to orderdetail page
@bp.route('/check')
def check():
    return render_template('CheckOutPage.html')


# Add function
@bp.route('/add/<int:toyid>', methods=['POST'])
def add(toyid):
    toy = Toy.query.get_or_404(toyid)

    # Check if order exists in session
    if 'order_id' in session:
        order_id = session.get('order_id')
        order = Order.query.get(order_id)
        if order is None:
            flash('Order not found.')
            order = createOrder()
            
    else:
        # If no order exists in session, create a new order
        order = createOrder()

    # Check if the toy is already in the order
    order_detail = Order_detail.query.filter_by(order_id=order.id, toy_id=toyid).first()
    if order_detail is None:
        # If the toy is not already in the order, add it
        new_order_detail = Order_detail(order_id=order.id, toy_id=toyid, amount=1, total_price=toy.price)
        db.session.add(new_order_detail)
    else:
        # If the toy is already in the order, increase the amount
        order_detail.amount += 1
        order_detail.total_price = toy.price * order_detail.amount

    try:
        db.session.commit()
        flash('Toy added to the order successfully!')
    except Exception as e:
        db.session.rollback()
        flash(f'Error adding toy to the order: {e}')

    return redirect(url_for('main.index'))

@bp.route('/subtract/<int:toyid>', methods=['POST'])
def subtract(toyid):
    if 'order_id' not in session:
        flash('No active order found.')
        return redirect(url_for('main.index'))
    
    order_id = session.get('order_id')
    order_detail = Order_detail.query.filter_by(order_id=order_id, toy_id=toyid).first()

    if order_detail is None:
        flash('Toy not found in the order.')
        toys = Toy.query.order_by(Toy.name).all()
        flash('Toy amount updated successfully!')
        return render_template('Homepage.html', toys = toys, orders = [])
    
    if order_detail.amount > 1:
        order_detail.amount -= 1
        order_detail.total_price = order_detail.toy.price * order_detail.amount


    else:
        db.session.delete(order_detail)
        orders = Order_detail.query.filter_by(order_id=order_detail.order_id)
        if orders is None:
            db.session.commit()
            toys = Toy.query.order_by(Toy.name).all()
            flash('Toy amount updated successfully!')
            return render_template('Homepage.html', toys = toys, orders = [])
  
    try:
        db.session.commit()
        flash('Toy amount updated successfully!')
        

    except Exception as e:
        db.session.rollback()
        flash(f'Error updating toy amount: {e}')

    return redirect(url_for('main.index'))

def checkorder():
    order = Order_detail.query.order_by(Order_detail.order_id.desc()).first()
    if order is not None:
        orders = Order_detail.query.filter(Order_detail.order_id == order.order_id).all()
    else:
        orders = []
    return orders

def createOrder():
    order = Order()
    db.session.add(order)
    db.session.flush()
    session['order_id'] = order.id
    return order

N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/CheckOutPage.html
{% extends 'base.html' %}

{% block header %}
<div id="navigationbar">
    <div id="companyname">
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
        <a href="#">My Fantastic Toy Shop</a>
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
    </div>
    <nav id="navigationmenu">
        <ul id="navigationlist">
            <li>
                <a href="{{url_for('main.index')}}">
                    <img style="height: 24px; width: 24px;" src="{{url_for('static', filename='image/Icon/back.png')}}" alt="back">
                    Back
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block main %}
<div class="container col-md-6">
    <h2>Insert Your Details:</h2>
    
    <form action="{{url_for('main.checkout')}}", methods="POST">
       
      <div class="form-group">
        <label for="firstname">First name:</label>
        <input type="text" class="form-control" id="firstname" placeholder="Enter first name" name="firstname">
      </div>
    
      <div class="form-group">
        <label for="lastname">Lastname:</label>
        <input type="text" class="form-control" id="lastname" placeholder="Enter lastname" name="lastname">
      </div>
  
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
      </div>
  
      <div class="form-group">
        <label for="address">Adress:</label>
        <input type="text" class="form-control" id="address" placeholder="Enter address" name="address">
      </div>
  
      <button type="submit" class="btn btn-default" style="border-radius: 4px; background-color: rgb(255, 115, 60); border-color: black;border-width: 1px; height: 30px; width: 90px;">
            <div class="list">
                <p style="color: white;">
                    Submit
                </p>
            </div>
        </button>
   
    </form>
  </div>
{% endblock %}

N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/Orderdetail.html
<!-- All of the code is from Ian #Bryan -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="My Fantastic Toy Shop" />
    <title>My Fantastic Toy Shop</title>
  
</head>
<body style="background-color: lightsalmon;">

        <div class="container col-md-6">
          <h2>Checkout Form</h2>
          
          <form action="{{url_for('main.checkout')}}", methods="POST">
             
            <div class="form-group">
              <label for="firstname">First name:</label>
              <input type="text" class="form-control" id="firstname" placeholder="Enter first name" name="firstname">
            </div>
          
            <div class="form-group">
              <label for="lastname">Lastname:</label>
              <input type="text" class="form-control" id="lastname" placeholder="Enter lastname" name="lastname">
            </div>
        
            <div class="form-group">
              <label for="email">Email:</label>
              <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
            </div>
        
            <div class="form-group">
              <label for="address">Adress:</label>
              <input type="text" class="form-control" id="address" placeholder="Enter address" name="address">
            </div>
        
            <button type="submit" class="btn btn-default">Submit</button>
         
          </form>
        </div>
    
    <!-- Footer of the website -->
    <footer>
        <div class="footer">
            <p>Copyright &copy; 2024</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</body>
</html>

N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/ProductDetailPage.html
{% extends 'base.html' %}


{% block header %}
<div id="navigationbar">
    <div id="companyname">
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
        <a href="#">My Fantastic Toy Shop</a>
        <img class="imgTitleIcon" src="{{url_for('static', filename='image/Icon/titleToy.png')}}" alt="shopping">
    </div>
    <nav id="navigationmenu">
        <ul id="navigationlist">
            <li>
                <a href="{{url_for('main.index')}}">
                    <img style="height: 24px; width: 24px;" src="{{url_for('static', filename='image/Icon/back.png')}}" alt="back">
                    Back
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block main %}

<section>
    <div style="align-items: center; border-bottom: 4px solid white; margin-left: 10%; margin-right: 10%; margin-top: 3%;" id="productdetail">
        <div class="d-flex flex-row">
            <div class="p-2">
                <img src="{{url_for('static', filename='image/Icon/info.png')}}" alt="info" style="height: 36px; width: 36px;">
            </div>
            <div class="p-2">
                <div style="height: 50px; width: 300px; margin-left: -5%;">
                    <h2 style="color: white;">Toy Detail:</h2>
                </div>
            </div> 
        </div>

        <div class="d-flex flex-column">
            <div class="p-2" style="margin-top: -1%; width: 300px;">
                <img src="{{url_for('static', filename='image/'+toy.image)}}" alt="toyImg" style=" width: 300px; height: 300px; border-radius: 4px; border: 4px solid white;">
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Name:</h2>
                <p style="color: white; display: inline; margin-left: 1%;">{{toy.toy_name}}</p>
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Price:</h2>
                <p style="color: white; display: inline; margin-left: 1%;">${{toy.price}}</p>
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Category:</h2>
                <p style="color: white; display: inline; margin-left: 1%;">{{toy.category_name}}</p>
            </div>

            <div class="p-2" style="margin-top: -1%;">
                <h2 style="color:white; display: inline;">Description:</h2>
                <p style="color: white; display: inline; margin-left: 1%;"><br>{{toy.description}}</p>
            </div>

            <div class="p-2">
                <!-- Add function #Bryan -->
                <form method="post" action="{{url_for('main.add', toyid=toy.id)}}">
                    <button style="background-color: rgb(255, 115, 60); width: 180px; height: 60px; border-radius: 30px; border-color: rgb(215, 95, 50); color: white;">
                        Add In Cart!
                        <img src="{{url_for('static', filename='image/Icon/add-to-cart.png')}}" alt="details" style="height: 44px;width: 44px;">
                    </button>
                </form>
            </div>
        </div>  
    </div>
</section>

<div>
    <!-- Cart button -->
    <div class="float">
        <a href="#order-detail">
            <img src="{{url_for('static', filename='image/Icon/shopping-cart.png')}}" alt="Cart" style="height: 50px; width: 50px; margin-top: 15px;">
        </a>
        
    </div>

    <!-- Order Detail -->
    <div id="order-detail" class="modal">
        <div class="content" style=" width: 60em;">
            <h2 style="color: black; position:absolute; top:10px; right: 12em; ">
                Order Detail
            </h2>

            <!-- ORder list #Bryan -->
            <div class="container">
                <div class="row">
                    <div class="col list">
                        <p>Toy Name</p>
                    </div>
                    <div class="col list">
                        <p>Toy Price</p>
                    </div>
                    <div class="col list">
                        <p>Total Price</p>
                    </div>
                    <div class="col-6 list">
                        <p>Amount</p>
                    </div>
                </div>
                
                <!-- For loop -->
                {% if orders %}
                {% for order in orders %}
                <div class="row">
                    <div class="col list">
                        <p>
                            {{order.toy.name}}
                        </p>
                    </div>
                    <div class="col list">
                        <p>
                            ${{order.toy.price}}
                        </p>
                    </div>
                    <div class="col list">
                        <P>
                            {{order.total_price}}
                        </P>
                    </div>
                    <div class="col list" style="height: 24px; width: 24px;">
                        <form method="post" action="{{url_for('main.subtract', toyid=order.toy_id)}}">
                            <button type="submit" style="border-color: transparent;">
                                <img src="{{url_for('static', filename='image/Icon/minus.png')}}", alt="subtract" style="height: 24px; width: 24px;">
                            </button>
                        </form> 
                    </div>
                    <div class="col list">
                        <P>
                            {{order.amount}}
                        </P>
                    </div>
                    <div class="col list" style="height: 24px; width: 24px;">
                        <form method="post" action="{{url_for('main.add', toyid=order.toy_id)}}">
                            <button type="submit" style="border-color: transparent;">
                                <img src="{{url_for('static', filename='image/Icon/plus.png')}}", alt="plus" style="height: 24px; width: 24px;">
                            </button>
                        </form>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <p class="list" style="color: red;">
                    No toy inside cart.
                </p>
                {% endif %}
            </div>
            
            <a href="{{url_for('main.check')}}" style="position: absolute; bottom: 10px; right: 20px">
                <button type="button" style="border-radius: 4px; background-color: rgb(255, 115, 60); border-color: black;border-width: 1px; height: 30px; width: 90px;">
                    <p style="color: white;">
                        Checkout!
                    </p>
                </button>
            </a>
            
            <a href="#" style=" position: absolute; top: 10px; right: 10px;">
                <img src=".{{url_for('static', filename='image/Icon/cancel.png')}}" alt="cancel" style="height: 24px;width: 24px;">  
            </a>
        </div>
    </div>
</div>

<!-- Relative Product -->
<section>
    <div style="align-items: center; margin-left: 10%; margin-right: 10%;margin-top: 1%; margin-bottom: 5%;" id="relatedtoys">
        <div class="d-flex flex-row">
            <div class="p-2">
                <img src="{{url_for('static', filename='image/Icon/related-toys.png')}}" alt="info" style="height: 36px; width: 36px;">
            </div>
            <div class="p-2">
                <div style="height: 50px; width: 300px; margin-left: -5%;">
                    <h2 style="color: white;">Related Toys:</h2>
                </div>
            </div> 
        </div>

        <div class="container" style="padding: 5px; background-color: rgb(185, 80, 25);">
            <div class="scrolling-wrapper">

                {% for Toy in toys %}
                <a href="{{url_for('main.toydetail', toyid=Toy.id)}}">
                    <div class="card_Product_related">
                        <img class="card-img-top" src="{{url_for('static', filename='image/'+Toy.image)}}" alt="Card name">
                        <div class="card-body">
                          <p class="card-text" style="color: black;">{{Toy.name}}</p>
                        </div>
                    </div>
                </a>
                {% endfor %}

            </div>
        </div>
    </div>
</section>
{% endblock %}

N11740388_Wu-Hsuan_Chen_IFN557_Assignment/MyFantasticToyShop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="My Fantastic Toy Shop" />
    <title>My Fantastic Toy Shop</title>
  
</head>
<body style="background-color: lightsalmon;">
    
    <!-- Contains the heading, navigation and banner image -->
    <header>
        {% block header %}{% endblock %}
    </header>

    <!-- Contains the main content of the website, divided into sections -->
    <main>
        {% block main %}{% endblock %}
    </main>

    

    <!-- Footer of the website -->
    <footer>
        <div class="footer list">
            <p>Copyright &copy; 2024</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</body>
</html>